name: sex
favicon: null
layout_spectrum: 0.9486374584957957
typography_spectrum: 0.0871583498083055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.2093141560908407
purpose:
  - name: follow
    item: null
    url: null
